In [2]:
import torch

In [2]:
tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print(tensor.dtype, tensor.shape, sep='|')
tensor = tensor.to(dtype=torch.float64)
print(tensor.dtype)

torch.int32|torch.Size([3])
torch.float64


In [13]:
n = 10_000
custom_shape = (n,n)
a = torch.rand(custom_shape)
b = torch.rand_like(a)

In [8]:
%%timeit
a+b

24.3 ms ± 3.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%%timeit
torch.add(a,b)

24.5 ms ± 2.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
del a, b

In [100]:
a = torch.randint(low=1, high=10, size=(2,2,2))
a = a.to(torch.float64)
print(
        a,
        a.min(),
        a.argmin(),
        a.max(),
        a.argmax(),
        sep='\n'
        )

tensor([[[6., 6.],
         [9., 3.]],

        [[9., 8.],
         [3., 2.]]], dtype=torch.float64)
tensor(2., dtype=torch.float64)
tensor(7)
tensor(9., dtype=torch.float64)
tensor(2)


In [81]:
x = torch.arange(start=0, end=10, dtype=torch.float64)
x.shape

torch.Size([10])

In [57]:
torch.stack([x,x,x,x], dim = 0)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [76]:
x.reshape(1,1,-1).squeeze().shape

torch.Size([10])

In [108]:
y = torch.rand_like(x)
y = y.reshape(1,1,-1)
y.unsqueeze(0)

tensor([[[[0.9285, 0.1711, 0.4778, 0.8404, 0.5929, 0.9988, 0.6958, 0.2536,
           0.3420, 0.2825]]]], dtype=torch.float64)

In [164]:
x = torch.arange(1,10, dtype=torch.float64).reshape(1,3,-1)
x, torch.diagonal(x, dim1=1, dim2=2)


(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]], dtype=torch.float64),
 tensor([[1., 5., 9.]], dtype=torch.float64))

In [199]:
RANDOM_SEED = 45

torch.manual_seed(RANDOM_SEED)
x = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
y = torch.rand_like(x)

condition = x==y
if condition.unique().sum() != 1:
    raise ValueError('x and y should be equal')

In [206]:
device = "cuda" if torch.cuda.is_available() else "cpu"